### ISSUE TITLE
Remove submodule jedi

### ISSUE THREAD

**Issue by Shougo** [deoplete-plugins/deoplete-jedi#194]
deoplete-jedi should not include jedi.
It should use system jedi instead.

Because, it is not easy to follow upstream changes.

**Comment by blueyed** [comment]
Hmm, not sure if this is a good idea..
Shipping/pinning the submodule allows us to target a specific version - otherwise we would need to support older versions, too etc.

**Comment by Shougo** [comment]
I think deoplete-jedi should only supports the latest version of jedi.
I don't want to update jedi in the repository...

**Comment by blueyed** [comment]
> I think deoplete-jedi should only supports the latest version of jedi.

Well, you know how long it took (and still takes) to update it for the new environment API?

Also distributions might not have the latest jedi themselves.

> I don't want to update jedi in the repository...

What is the problem with that?

**Comment by Shougo** [comment]
> Well, you know how long it took (and still takes) to update it for the new environment API?
> Also distributions might not have the latest jedi themselves.

But user can install/update jedi by `pip3` easily.
neovim package is already installed by `pip3`.  I think it is not problem.

> What is the problem with that?

It is very wired instructions.
Please tell the jedi update instructions for me.

**Comment by JoveYu** [comment]
jedi has a stable api now, may be use latest one is better

**Comment by airhuman** [comment]
I agree with @Shougo , use the system jedi

**Comment by astier** [comment]
Yes system jedi.
