### ISSUE TITLE
autocomplete error

### ISSUE THREAD

**Issue by travis-tang** [deoplete-plugins/deoplete-jedi#224]
### Problem summary
```
import multiprocessing as mp

mp.pool.Pool()
mp.Pool()
```
When I use `import multiprocessing as mp`, it cannot autocomplete for `mp.Pool()`, but it works well for `mp.pool.Pool()`. And the right usage is former.
![2019-04-09_17:44:16_select](https://user-images.githubusercontent.com/46301849/55790990-24f1fb80-5af0-11e9-9cfc-a6165aeeb63c.png)
![2019-04-09_17:44:33_select](https://user-images.githubusercontent.com/46301849/55791004-291e1900-5af0-11e9-9e36-20fa8226edef.png)
### Environment Information
- OS: Arch
- vim version: 8.1.1073-1

**Comment by Shougo** [comment]
It seems not deoplete-jedi's problem.
Please test the completion in jedi only.

**Comment by Shougo** [comment]
I think `mp.Pool()` is invalid.
Why `mp.pool.Pool()` is valid.
Because `mp.pool` is module name.

**Comment by Shougo** [comment]
It seems jedi problem.
Please ask it in jedi repository.

https://github.com/davidhalter/jedi/issues

**Comment by Shougo** [comment]
I have reproduced the result in pyls(it uses jedi internally), so I don't think it is deoplete-jedi's problem.

**Comment by travis-tang** [comment]
Cause it shows **AttributeError** when I use latter. Thanks for you answer.

**Comment by travis-tang** [comment]
I `import multiprocessing.pool` again, it has no problem.
