### ISSUE TITLE
Completion outside pyenv with python3_host_prog set

### ISSUE THREAD

**Issue by dvd42** [deoplete-plugins/deoplete-jedi#232]
# Problem summary
I usually work with pyenv for some projects only. If I set my python3_host_prog to my neovim3 pyenv python path. Completion works like a charm for every module in any python virault environment. However when I am working on a project which is not on any virtual environment I cant get completion for modules such as numpy, pandas, torch, etc...

## Expected (Inside pyenv)
![image](https://user-images.githubusercontent.com/22733646/61968804-3694db80-afd9-11e9-96a7-5760fec87695.png)

## Actual (Outisde pyenv with python3_host_prog set)

![image](https://user-images.githubusercontent.com/22733646/61968854-56c49a80-afd9-11e9-9ea6-440e3ad7169d.png)

## Environment Information

 * OS: Linux Mint 19
 * Neovim version: 

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" *** Deoplete *** 
let g:deoplete#enable_at_startup = 1
let g:python3_host_prog = expand("~/.pyenv/versions/neovim3/bin/python")

let g:deoplete#auto_complete=1
let g:deoplete#sources#jedi#enable_typeinfo = 0 "gotta go fast
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif "automatically closing the scratch window at the top of the vim window on finishing a complete or leaving insert
```
Is this expected behaviour? I wouldn't want to have to change the python3_host_prog variable whenever I am outside pyenv. Is there a way to get the best of both worlds here? 

**If this is not expected behaviour, let me know and I can post the logs** 
Thanks in advance!!

**Comment by Shougo** [comment]
> Is this expected behaviour? I wouldn't want to have to change the python3_host_prog variable whenever I am outside pyenv. Is there a way to get the best of both worlds here?

Unfortunately, this is the feature of jedi.
jedi detects pyenv environment automatically.
