### ISSUE TITLE
No autocomplete after variable assignment

### ISSUE THREAD

**Issue by omaranbari** [deoplete-plugins/deoplete-jedi#233]
# Problem summary
Let's say I create: df = pd.DataFrame()

If I write df. immediately after the declaration, I get the expected auto-completion.

Now If I assign the variable, for instance by writing df = pd.read_excel('some/file/path.xlsx'), and on the subsequent line I type df. , I don't get any jedi auto-completion, just the member (with [M] flags)

## Expected
Get the same auto completion after variable assignment

## Environment Information

 * OS: arch linux
 * Neovim version: NVIM v0.5.0-111-g0c1be45ea

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('jedi', 'is_debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```
" ====================================
" Deoplete and autocompletion
" ====================================
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#notmuch#command = ['notmuch', 'address', '--format=json', '--deduplicate=address', '*']
call deoplete#custom#source('jedi', 'is_debug_enabled', 1)

"close preview window after autocompletion
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

"Show documentation below
set splitbelow

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

 1. Declare variable as: df = pd.DataFrame()
 2. type df. and wait for autocompletion
 3. Assign variable as: df = pd.read_excel('some-file.xlsx')
 4. type df. , wait for auto completion, doesn't show up

## Screen shot (if possible)
![screen1](https://user-images.githubusercontent.com/31032827/67633547-71552b00-f8ca-11e9-9aa8-f88c871bc24e.png)

![screen2](https://user-images.githubusercontent.com/31032827/67633542-64383c00-f8ca-11e9-880a-f217ac563464.png)

**Comment by Shougo** [comment]
I think jedi doesn't support the feature.
Please test jedi.

**Comment by omaranbari** [comment]
It works in ipython which, apparently, is based on jedi. I haven't tested in vim yet but I can try this later if required.

**Comment by Shougo** [comment]
You can test vim-jedi instead.

**Comment by omaranbari** [comment]
You're correct. jedi-vim does not support this either. 
I will open an issue there and see if they can support.
Thank you.

**Comment by Shougo** [comment]
OK.
