### ISSUE TITLE
Python completion sometimes produce noise

### ISSUE THREAD

**Issue by peterbjorgensen** [deoplete-plugins/deoplete-jedi#234]
# Problem summary
Mostly completion works, but sometimes a lot of garbage characters are written instead of the actual completion. See the attached gif.

## Environment Information

 * OS: Arch linux with kernel 5.3.7
 * Neovim version: 0.4.2-2

## Provide a minimal init.vim with less than 50 lines (required)

```vim
let g:deoplete#enable_at_startup = 1
```

 1. nvim -u minimal.vimrc

## Steps to reproduce the issue after starting Neovim (required)

 1. open neovim with minimal vimrc
 2. try to do autocompletion

## Screen shot (if possible)

![jedi-vim-garbled-characters](https://user-images.githubusercontent.com/121425/67705194-d5551d80-f9b6-11e9-8cb4-cde336de602b.gif)

**Comment by blueyed** [comment]
That's from jedi-vim's conceal hack for signatures.
Please consider trying https://github.com/davidhalter/jedi-vim/pull/652, or use the cmdline window instead.
