### ISSUE TITLE
no module named 'deoplete.base'

### ISSUE THREAD

**Issue by Quoteme** [deoplete-plugins/deoplete-jedi#251]
# Problem summary
Just did a fresh install of deoplete, python-jedi and then deoplete-jedi and I encounter this errer every time I try to edit a python file and also when doing :PlugInstall

## Environment Information

 * OS: Arch Linux latest (kernel: 5.5.5-arch1-1)
 * Neovim version: NVIM v0.4.3

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
Plug 'deoplete-plugins/deoplete-jedi'

let g:deoplete#enable_at_startup = 1
```

## Generate logfiles if appropriate
```
[deoplete] Traceback (most recent call last):
  File "/home/luca/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 97, in _add_source
    Source = import_plugin(path, 'source', 'Source')
  File "/home/luca/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 55, in import_plugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/luca/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 5, in <m
odule>
    from deoplete.base.source import Base
ModuleNotFoundError: No module named 'deoplete.base'
Could not load source: /home/luca/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py.
```
This shows up, after entering insert mode in a python file

## Steps to reproduce the issue after starting Neovim (required)

 1. install deoplete, python-jedi and deoplete-jedi
 2. open neovim on a python file
 3. enter insert mode

## Screen shot (if possible)
![screenshot](https://i.imgur.com/d9dkxvm.png)

**Comment by Shougo** [comment]
I don't reproduce the problem.
I think your deoplete version is not the latest

And this is wrong.

```
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
Plug 'deoplete-plugins/deoplete-jedi'
```

`call plug#end()` must be after `Plug 'deoplete-plugins/deoplete-jedi'`.

**Comment by Quoteme** [comment]
yes, the version was the problem.
`python-msgpack` in the official arch linux repositories is version 0.6.2
running
`sudo pip3 install -U msgpack`
solved the issue

**Comment by Shougo** [comment]
OK.
