### ISSUE TITLE
Should `which pyenv` return a shell function in Fish?

### ISSUE THREAD

**Issue by jooize** [deoplete-plugins/deoplete-jedi#259]
> To confirm you have pyenv correctly installed, run which pyenv. It should print a shell function, not a file path.

— https://github.com/deoplete-plugins/deoplete-jedi/wiki/Setting-up-Python-for-Neovim#tips-for-using-pyenv

Using Fish shell:

```fish
which pyenv
```
```
/Users/Esko/.config/pyenv/bin/pyenv
```

Seems to function as I expected, but perhaps issues will surface.

Also, `:h nvim-python` results in:

> E149: Sorry, no help for nvim-python

**Comment by Shougo** [comment]
> Also, :h nvim-python results in:

Please read `:help provider-python` instead.

> Seems to function as I expected, but perhaps issues will surface.

I don't know about it.  Because I don't written the page.

**Comment by Shougo** [comment]
I think `which pyenv` shell function is not needed.
What is the issue you happened?

Please describe it more clearly.

**Comment by Shougo** [comment]
No response
