### ISSUE TITLE
Latest version of jedi crash on Windows

### ISSUE THREAD

**Issue by jdhao** [deoplete-plugins/deoplete-jedi#261]
# Problem summary

Latest version (0.17.0) or master branch of Jedi will crash on Windows, as reported [here](https://github.com/davidhalter/jedi/issues/1627). Since deoplete-jedi depends on Jedi, I think it should be reported here too.

Older versions Jedi works well. I wonder if there is way to specify Jedi version to use for deoplete-jedi?

**Comment by Shougo** [comment]
Unfortunately you cannot specify the version.
deoplete-jedi includes jedi.
If it is fixed in upstream, I will include the changes.

**Comment by jdhao** [comment]
Maybe jedi should be decoupled from deoplete-jedi so that users can upgrade or downgrade Jedi more freely, as discussed [here](https://github.com/davidhalter/jedi/issues/1627). 

Currently, I have to go to the directory where jedi is embedded in deoplete-jedi  (On my system, the directory is: `C:\Users\Administrator\AppData\Local\nvim-data\plugged\deoplete-jedi\rplugin\python3\deoplete\vendored\jedi`) and checkout the old commit like this:

```
git checkout tags/v0.16.0
```

It is a bit cumbersome as compared to `pip install -U jedi==0.16.0`.

**Comment by Shougo** [comment]
Yes.  But users needs to install/upgrade jedi module manually.
It is really desired behavior?
I need more users voice.

**Comment by jdhao** [comment]
@Shougo As long as you state explicitly on the repo home page which versions of  Jedi are required for deoplete-jedi to work properly, I think it is the user's responsibility to meet that requirement. The plugin shouldn't do that for the user unless explicitly instructed by the user.

For example,  deoplete requires certain Python versions to run, but it shouldn't install Python for the user. It is the user who need to fulfill that requirement.

**Comment by Shougo** [comment]
@jdhao Please test https://github.com/deoplete-plugins/deoplete-jedi/pull/262.

**Comment by jdhao** [comment]
@Shougo  It works. I can use jedi 0.16 with deoplete-jedi without any error.

**Comment by Shougo** [comment]
I will merge it later.

**Comment by Shougo** [comment]
I have merged it.
