### ISSUE TITLE
Changing the kind/type of completion-matches

### ISSUE THREAD

**Issue by astier** [deoplete-plugins/deoplete-jedi#263]
I didn't fill out all of the required information because its just a feature request. But can do so if necessary.

The completion-matches have all a type/kind like function, module, statement, etc. Is it possible modify them? I would like to abbreviate it to f, m, s, etc. to save some space and make the completions more compact.

Turn this:

![2020-08-05-131714_528x124_scrot](https://user-images.githubusercontent.com/36510152/89406813-fef95d00-d71d-11ea-999f-c5a3f40809a1.png)

into something like this:

![2020-08-05-131622_233x125_scrot](https://user-images.githubusercontent.com/36510152/89406735-ea1cc980-d71d-11ea-9d9f-65b510ccf3d0.png)

**Comment by Shougo** [comment]
Please use `g:deoplete#sources#jedi#short_types` for it.

Why don't read the documentation?

To change deoplete-jedi mark:

```vim
call deoplete#custom#source('jedi', 'mark', 'JD')
```

**Comment by astier** [comment]
### Short Types

I didn't read the documentation about `g:deoplete#sources#jedi#short_types` because I can not find any documentation about `deoplete-jedi` except in the README.md. But `g:deoplete#sources#jedi#short_types` is not mentioned there.
- Where can I find documentation for `g:deoplete#sources#jedi#short_types`?
- So its not possible to define your own short_types?

### Mark

I dont think `call deoplete#custom#source('jedi', 'mark', 'JD')` works as intended. Now it shows `JD` additionally to `[jedi]`.

![2020-08-06-032010_483x140_scrot](https://user-images.githubusercontent.com/36510152/89479731-d1e79180-d793-11ea-8a58-bcdd2cfeeb94.png)

### Minimal vimrc

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'deoplete-plugins/deoplete-jedi'
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
cal plug#end()
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#short_types = 1
cal deoplete#custom#source('jedi', 'mark', 'JD')
```

**Comment by Shougo** [comment]
> Where can I find documentation for g:deoplete#sources#jedi#short_types?

README.md in the repository.

> So its not possible to define your own short_types?

Yes.

**Comment by Shougo** [comment]
> I dont think call deoplete#custom#source('jedi', 'mark', 'JD') works as intended. Now it shows JD additionally to [jedi].

It is bug of deoplete-jedi.  I will fix it later.

**Comment by Shougo** [comment]
```vim
let g:deoplete#sources#jedi#enable_short_types = 1
let g:deoplete#sources#jedi#short_types_map = {
      \ 'module': 'M',
      \ 'function': 'f',
      \ 'statement': 'v',
      \}
cal deoplete#custom#source('jedi', 'mark', 'JD')
call deoplete#custom#source('jedi', 'converters', ['converter_word_abbr'])
```

**Comment by Shougo** [comment]
I have added the documentation for it.

**Comment by astier** [comment]
Thank you. It works. Maybe `g:deoplete#sources#jedi#enable_short_types` is not required anymore and could be deleted? You could just check if `g:deoplete#sources#jedi#short_types_map` is set.

**Comment by Shougo** [comment]
> Thank you. It works. Maybe g:deoplete#sources#jedi#enable_short_types is not required anymore and could be deleted? 

No.  Because `short_types_map` just overwrite short_type defaults map.
You need to enable short type feature.
