### ISSUE TITLE
Dont add parameter-information to functions

### ISSUE THREAD

**Issue by astier** [deoplete-plugins/deoplete-jedi#264]
I didn't fill out all of the required information because its just a feature request. But can do so if necessary.

The completion-matches of kind function have the parameters attached to them. Examples can be seen in the first screenshot for the functions `access` and `add_dll_directory`. Is it possible remove them? I want to save some space and make the completions more compact.

Turn this:

![2020-08-05-131714_528x124_scrot](https://user-images.githubusercontent.com/36510152/89406813-fef95d00-d71d-11ea-999f-c5a3f40809a1.png)

into something like this:

![2020-08-05-131622_233x125_scrot](https://user-images.githubusercontent.com/36510152/89406735-ea1cc980-d71d-11ea-9d9f-65b510ccf3d0.png)

**Comment by Shougo** [comment]
`:help converter_remove_paren`

```
				*deoplete-filter-converter_remove_paren*
converter_remove_paren
		It removes parentheses character in a candidate's word.
```

**Comment by astier** [comment]
It doesn't work. I am using `NVIM v0.5.0-622-gf26df8bb6`. Here is my minimal vimrc:

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'deoplete-plugins/deoplete-jedi'
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
cal plug#end()
let g:deoplete#enable_at_startup = 1
cal deoplete#custom#source('_', 'converters', ['converter_remove_paren'])
```

Here is what I get:

![2020-08-06-030124_527x142_scrot](https://user-images.githubusercontent.com/36510152/89478741-25a4ab80-d791-11ea-9d21-581713b15951.png)

I am talking about not displaying paranthesis and the parameters in the pummenu.
`access(path: _FdOrPathType, mode: int, ...)` should be just `access`.

Also I did read your documentation. But I always understood `converter_remove_paren` such that it would prevent deoplete from auto-inserting paranthesis after selecting a completion. Also when I read your FAQ which refers to the following issue thats how I understood it https://github.com/Shougo/deoplete.nvim/issues/150

**Comment by Shougo** [comment]
OK.  I get it.  `converter_remover_paren` is for `word` attr only.
I will add new converter for it.

**Comment by Shougo** [comment]
I have added `converter_word_abbr`.

```vim
call deoplete#custom#source('jedi', 'converters', ['converter_word_abbr'])
```

**Comment by astier** [comment]
Thank you. It works. Except for one minor bug. In combination with `converter_auto_paren` the wrong order of both converters appends one `(` at the end of functions in the pummenu. The following setting:

```vim
cal deoplete#custom#source('jedi', 'converters', [
    \'converter_auto_paren',
    \'converter_word_abbr',
\])
```
produces this:

![2020-08-06-134521_324x147_scrot](https://user-images.githubusercontent.com/36510152/89528306-194d3c80-d7eb-11ea-84ac-9013efb8c847.png)

`access(` should be `access`. If you switch the order of both converters it works correctly:

```vim
cal deoplete#custom#source('jedi', 'converters', [
    \'converter_word_abbr',
    \'converter_auto_paren',
\])
```

**Comment by Shougo** [comment]
> Except for one minor bug. In combination with converter_auto_paren the wrong order of both converters appends one ( at the end of functions in the pummenu. 

It is not bug.
You should understand what you do.
`converter_auto_paren` changes `word` and `converter_word_abbr` change `abbr` to `word`.
It is expected behavior!
