### ISSUE TITLE
deoplete-jedi crashes when trying to complete pandas DataFrame attributes

### ISSUE THREAD

**Issue by PorcelainMouse** [deoplete-plugins/deoplete-jedi#272]
# Problem summary
deoplete-jedi can find some names in pandas namespace, but crashes when trying to find all attributes of a DataFrame object or pd.DataFrame itself.

## Expected
no crash

## Environment Information

 * OS: GNU/Linux (Fedora 35)
 * Neovim version: v0.6.0

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
" Your minimal init.vim
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim/
set runtimepath+=~/.local/share/nvim/plugged/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('jedi', 'is_debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.
[deoplete.log](https://github.com/deoplete-plugins/deoplete-jedi/files/7820639/deoplete.log)

I tried looking at these, but I couldn't see anything more useful than the error nvim reports to the console, itself.

## Steps to reproduce the issue after starting Neovim (required)

 1. `import pandas as pd`
 2. `pd.DataFrame.`
 3. or
 ```
import pandas as pd
df = pd.DataFrame()
df.
```

## Upload the logfile(s)
[deoplete.log](https://github.com/deoplete-plugins/deoplete-jedi/files/7820634/deoplete.log)

**Comment by Shougo** [comment]
It works for me.  You must describe the error more clearly.
Closing.

![Uploading スクリーンショット_2022-01-07_08-24-26.png…]()

**Comment by Shougo** [comment]
And deoplete-jedi is very old plugin.  You should use LSP completion instead.

**Comment by Shougo** [comment]
It may be jedi's bug.  You should update jedi to the latest.
