### ISSUE TITLE
How to set autocomplete key to TAB?

### ISSUE THREAD

**Issue by vikomen** [deoplete-plugins/deoplete-jedi#273]
Hi, I am having issues figuring put how one could set the autocomplete key to TAB? Currently it is ENTER or CTR + SPACE.  I should also say that I am coming here from https://vim.fisadev.com. Any help will be  greatly appreciated.

**Comment by Shougo** [comment]
You can use the mapping.

```vim
inoremap <silent><expr> <TAB>
\ pumvisible() ? "\<C-n>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ deoplete#manual_complete()
function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}

```

**Comment by vikomen** [comment]
Hi. Thank you for the comment. Everything is working fine once I source my .vimrc explicitly. However, when I open a new file, the setting doesnt work. I need to source it again. Do you know why this could be occurring?

**Comment by Shougo** [comment]
I think your `<Tab>` is overwritten by other plugins.

You can test it by:
`verbose inoremap <Tab>`

**Comment by vikomen** [comment]
Hi, just a quick follow up. Where should I put this command? I am presuming in my .vimrc however I tried putting it exact;y bellow where I put your original comment but nothing is changing. Syr for this, but I am a complete beginner.

**Comment by Shougo** [comment]
the command is executed when Tab doesn't work.
It prints where overwrite the key.
