### ISSUE TITLE
Preview window doesn't show method signature 

### ISSUE THREAD

**Issue by eyalmazuz** [deoplete-plugins/deoplete-jedi#274]
# Problem summary
When using deoplete-jedi the preview window shows the docstring but doesn't show method signature unlike normal jedi that shows both

## Expected
showing method signature in the preview window

## Environment Information

 * OS: Manjaro KDE
 * Neovim version:
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
Features: +acl +iconv +tui

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Jedi related stuff
let g:deoplete#enable_at_startup = 1
let g:jedi#completions_enabled = 0
let g:deoplete#sources#jedi#show_docstring = 1
```

## Steps to reproduce the issue after starting Neovim (required)

 1. Installed jedi
 2. Installed deoplete-jedi
 3. installed deoplete

## Screen shot (if possible)

deoplete-jedi:
![image](https://user-images.githubusercontent.com/34383384/185559316-5d0d871d-c4e3-4535-afe0-96245067ed87.png)

and when using jedi-vim
```vim
" Jedi related stuff
let g:deoplete#enable_at_startup = 0
let g:jedi#completions_enabled = 1
let g:deoplete#sources#jedi#show_docstring = 0
```

I get
![image](https://user-images.githubusercontent.com/34383384/185559082-0837785a-91c9-46c2-9f1e-fe9a41e8ed7b.png)

**Comment by Shougo** [comment]
Sorry.  The plugin support is done and it is not bug.
Closing.

**Comment by pirocv** [comment]
Hi, I'm facing the same problem. 

> Sorry. The plugin support is done and it is not bug.
> Closing.

Could you explain a little bit more about this?
Do you mean it is not possible to show method signature with deoplete-jedi?

**Comment by pirocv** [comment]
@Shougo

**Comment by Shougo** [comment]
The plugin development is done.
I don't add the feature.
To show the method signature, you can use echodoc plugin.

https://github.com/Shougo/echodoc.vim

**Comment by pirocv** [comment]
@Shougo 
Thank you for your response.
Understand. I will definitely check the echodoc plugin.
